//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyloBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilterType()
        {
            this.Filtereds = new HashSet<Filtered>();
        }
    
        public int FTID { get; set; }
        public string FTName { get; set; }
        public string FTDesc { get; set; }
        public string FTCode { get; set; }
        public Nullable<int> FTType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filtered> Filtereds { get; set; }
    }
}
