//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyloBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MID { get; set; }
        public Nullable<int> MCID { get; set; }
        public Nullable<int> MUID { get; set; }
        public string MUName { get; set; }
        public string MDate { get; set; }
        public string MText { get; set; }
    }
}
